[package]
name = "pcgbg"
version = "0.1.0"
authors = ["Arthur Eubanks <ayueubanks@gmail.com>"]
edition = "2018"

[dependencies]
noise = "0.5.0"
rgb = "0.8"
lodepng = "2.0.0"
structopt = "0.2"

[patch.crates-io]
noise = { git = 'https://github.com/Razaekel/noise-rs', rev = '2b2217c2ce76fd6fe986844021e6bca96530d974' }
