[package]
name = "pcgbg"
version = "0.1.0"
authors = ["Arthur Eubanks <ayueubanks@gmail.com>"]
edition = "2018"

[dependencies]
approx = "*"
euclid = "*"
noise = "0.5.0"
num-traits = "*"
structopt = "0.2"
ndarray = "*"
noisy_float = "*"

[dependencies.image]
version = "*"
default-features = false
features = ["png_codec"]

[dependencies.rand]
version = "0.7"
features = ["small_rng"]

[patch.crates-io]
noise = { git = 'https://github.com/Razaekel/noise-rs', rev = '2b2217c2ce76fd6fe986844021e6bca96530d974' }
